version: "3.8"

services:
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "127.0.0.1:9109:80" # Bind to localhost and port 9109
    volumes:
      - html:/usr/share/nginx/html:rw
    restart: always

  sftp:
    image: atmoz/sftp:latest
    container_name: sftp_server
    ports:
      - "2222:22" # SFTP server listens on port 2222
    volumes:
      - html:/home/${SFTP_USER}/upload
    environment:
      SFTP_USERS: ${SFTP_USERS} # Read credentials from the .env file
    entrypoint: ["/bin/sh", "-c", "USER=$(echo ${SFTP_USERS} | cut -d':' -f1) && mkdir -p /home/${USER}/upload && exec /entrypoint"]
    restart: always
volumes:
  html:
