version: '3.8'

services:
  webserver:
    build:
      context: ./nginx
    container_name: nginx_server
    volumes:
      - html:/usr/share/nginx/html
    ports:
      - "127.0.0.1:9109:80"
    restart: always

  sftp:
    build:
      context: ./sftp
      dockerfile: Dockerfile
      args:
        SFTP_USER: ${SFTP_USER}
        SFTP_PASS: ${SFTP_PASS}
    environment:
      SFTP_USER: ${SFTP_USER}
      SFTP_PASS: ${SFTP_PASS}
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - ./html:/home/${SFTP_USER}/uploads
    restart: always

volumes:
  html:
