services:
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "127.0.0.1:9109:80" # Bind to localhost and port 9109
    volumes:
      - html_data:/usr/share/nginx/html
    restart: always

  sftp:
    image: atmoz/sftp:latest
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - html_data:/home/georadio/upload
    environment:
      SFTP_USERS: ${SFTP_USERS} # Read credentials from the .env file
    restart: always

volumes:
  html_data:
