version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn:dev
    container_name: openvpn
    ports:
     - "23:1194/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
