version: '3'

services:
  mariadb:
    image: bitnami/mariadb:latest
    env_file:
      - .env
    environment:
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
      MARIADB_USER: bn_moodle
      MARIADB_DATABASE: bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9008:8080'
    env_file:
      - prod.env
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: bn_moodle
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_LANG: pt
      MOODLE_SSLPROXY: yes
      MOODLE_HOST: moodle.portaldoradioamador.pt
      MOODLE_SITE_NAME: Portal do Radioamador
      MOODLE_USERNAME: admin
      MOODLE_EMAIL: admin@portaldoradioamador.pt
      PHP_POST_MAX_SIZE: 500m
      PHP_UPLOAD_MAX_FILESIZE: 500m
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
