version: "3.9"

services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto
    ports:
      - "1883:1883"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mosquitto_data: {}
  mosquitto_log: {}
