version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "8883:8883"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/portaldoradioamador/ssl.ca:/mosquitto/config/certs/ca.crt
      - /home/portaldoradioamador/ssl.cert:/mosquitto/config/certs/server.crt
      - /home/portaldoradioamador/ssl.key:/mosquitto/config/certs/server.key

volumes:
  mosquitto_data: {}
