version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "9108:9108"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mosquitto_data: {}
  mosquitto_log: {}
