version: "3.9"

name: sotaportugal_wp

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "127.0.0.1:9101:80"
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_NAME: wordpress_db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db_data:
  wordpress_data:
